# Updated automation using ha-pixoo integration directly
# Replace your existing "Display Title Artist and CoverArt on Pixoo" automation with this

alias: Display Title Artist and CoverArt on Pixoo (ha-pixoo)
description: Display media player info using native ha-pixoo integration
triggers:
  - entity_id:
      - media_player.kuche
      - media_player.verstarker
      - media_player.appletv
    attribute: entity_picture
    for:
      hours: 0
      minutes: 0
      seconds: 3
    trigger: state
  - entity_id:
      - media_player.verstarker
      - media_player.kuche
      - media_player.appletv
    attribute: media_title
    for:
      hours: 0
      minutes: 0
      seconds: 3
    trigger: state
conditions:
  - condition: template
    value_template: >
      {{ trigger.entity_id in ['media_player.kuche', 'media_player.verstarker',
      'media_player.appletv'] and state_attr(trigger.entity_id, 'source') != 'HDMI ARC' }}
actions:
  # Clear display first
  - action: pixoo.clear_display
    target:
      entity_id: light.pixoo_display

  # Display cover art (if available)
  - condition: template
    value_template: '{{ state_attr(trigger.entity_id, "entity_picture") is not none }}'
  - action: pixoo.display_image
    data:
      url: http://homeassistant.local:8123{{ state_attr(trigger.entity_id, "entity_picture") }}
    target:
      entity_id: light.pixoo_display

  # Wait for image to load
  - delay:
      seconds: 1

  # Display artist and title as scrolling text at bottom of screen
  - action: pixoo.display_text
    data:
      text: >
        {{ state_attr(trigger.entity_id, "media_artist") }}   {{ state_attr(trigger.entity_id, "media_title") }}
      color: "#FFFFFF"
      x: 0
      y: 48
      font: 2
      speed: 60
      text_id: 1
      scroll_direction: left
    target:
      entity_id: light.pixoo_display

mode: single
